In [4]:
import os 
import pandas as pd
path = "E:\AI\LibrariesForAI\Pandas\data"
inputPathFile = "supermarket_sales.csv"
# data = pd.read_csv("data/abcd.csv")
def summaryOfData(path,inputPathFile):
    pathandFileName = path+"\\"+inputPathFile
    extension = os.path.basename(pathandFileName).split(".")[1]  
    if extension=="csv":
        data = pd.read_csv(pathandFileName)
    elif extension == "xlsx":
        data = pd.read_excel(pathandFileName)
    elif extension == "xls":
        data = pd.read_excel(pathandFileName)
    elif extension == "json":
        data = pd.read_json(pathandFileName)
    else:
        print("Extension not found, Please recheck")
    print("The shape of the input data is : \n\n ",data.shape)
    print("*"*100+"\n")
    print("Data type of the input data is :\n\n ",data.dtypes)
    print("*"*100+"\n")
    print("Head of input data is : \n\n",data.head(2))
    print("*"*100+"\n")
    print("Tail of input data is : \n\n",data.tail(2))
    print("*"*100+"\n")  
    print("The basic Information about input data : \n\n")
    print(data.info())
    print("*"*100+"\n")
    print("Describe the input data : \n\n",data.describe())
    print("*"*100+"\n") 
    print("Describe about object in the input data : \n\n",data.describe(include='O'))
    print("*"*100+"\n")
    print("Null values in the input object : \n\n",data.isna().sum())
    print("*"*100+"\n")
summaryOfData(path,inputPathFile)

The shape of the input data is :

  (1000, 17)
****************************************************************************************************

Data type of the input data is :

  Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                       object
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object
****************************************************************************************************

Head of input data is :

     Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female
1  226-31-3081      C  Naypyitaw        Normal  Female

             Product line  Unit price  Quantity   Tax 5%     Total  \
0       Health and beauty       74.69         7  26.1415  548.9715
1  Electronic accessories       15.28         5   3.8200     80.22

         Date   Time  Payment    cogs  gross margin percentage  gross income  \
0  01-05-2019  13:08  Ewallet  522.83                 4.761905       26.1415
1  03-08-2019  10:29     Cash   76.40                 4.761905        3.8200

   Rating
0     9.1
1     9.6
****************************************************************************************************

Tail of input data is :

       Invoice ID Branch    City Customer type  Gender         Product line  \
998  347-56-2442      A  Yangon        Normal    Male   Home and lifestyle
999  849-09-3807      A  Yangon        Member  Female  Fashion accessories

     Unit price  Quantity  Tax 5%    Total       Date   Time Payment    cogs  \
998       65.82         1   3.291   69.111  2/22/2019  15:33    Cash   65.82
999       88.34         7  30.919  649.299  2/18/2019  13:28    Cash  618.38

     gross margin percentage  gross income  Rating
998                 4.761905         3.291     4.1
999                 4.761905        30.919     6.6
****************************************************************************************************

The basic Information about input data :


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   object
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(6), int64(1), object(10)
memory usage: 132.9+ KB
None
****************************************************************************************************

Describe the input data :

         Unit price     Quantity       Tax 5%        cogs  \
count  1000.000000  1000.000000  1000.000000  1000.00000
mean     55.672130     5.510000    15.379369   307.58738
std      26.494628     2.923431    11.708825   234.17651
min      10.080000     1.000000     0.508500    10.17000
25%      32.875000     3.000000     5.924875   118.49750
50%      55.230000     5.000000    12.088000   241.76000
75%      77.935000     8.000000    22.445250   448.90500
max      99.960000    10.000000    49.650000   993.00000

       gross margin percentage  gross income      Rating
count             1.000000e+03   1000.000000  1000.00000
mean              4.761905e+00     15.379369     6.97270
std               6.131498e-14     11.708825     1.71858
min               4.761905e+00      0.508500     4.00000
25%               4.761905e+00      5.924875     5.50000
50%               4.761905e+00     12.088000     7.00000
75%               4.761905e+00     22.445250     8.50000
max               4.761905e+00     49.650000    10.00000
****************************************************************************************************

Describe about object in the input data :

          Invoice ID Branch    City Customer type  Gender         Product line  \
count          1000   1000    1000          1000    1000                 1000
unique         1000      3       3             2       2                    6
top     750-67-8428      A  Yangon        Member  Female  Fashion accessories
freq              1    340     340           501     501                  178

          Total        Date   Time  Payment
count      1000        1000   1000     1000
unique      990          89    506        3
top     216.846  02-07-2019  19:48  Ewallet
freq          2          20      7      345
****************************************************************************************************

Null values in the input object :

 Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64
****************************************************************************************************

In [29]:
# summaryOfData(data)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               998 non-null    object
 1   Branch                   998 non-null    object
 2   City                     998 non-null    object
 3   Customer type            999 non-null    object
 4   Gender                   999 non-null    object
 5   Product line             1000 non-null   object
 6   Unit price               998 non-null    float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   object
 10  Date                     999 non-null    object
 11  Time                     999 non-null    object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(6), int64(1), object(10)
memory usage: 132.9+ KB